// Automatically generated by astro-icon
// 99595318caabb8ed00123b2fa901ec0d771f1018d853967d9d7e55a5eca42244

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "anchor"
		| "announcement"
		| "badge"
		| "ban"
		| "bits"
		| "bot"
		| "cat"
		| "copy"
		| "discord"
		| "door"
		| "erase"
		| "gift"
		| "gifts"
		| "github"
		| "home"
		| "manzdev"
		| "message"
		| "mtmi"
		| "rocket"
		| "star"
		| "streak"
		| "train"
		| "warning";
}